### PR TITLE
Spread the setOptions to pass initial settings to SunEditor Object

### LINKED ISSUE #167: HTML attributes being removed while it shouldn't
I'd like to let people edit HTML emails in the Sun Editor, when I paste the HTML via the Code View, it works good and shows the correct layout (with all the inline-styles and attributes). However, if I take the same string of HTML and set is as the defaultValue, it removes a lot of the markup. 

Playground:
https://codesandbox.io/s/unwanted-html-removal-on-load-7mpmm?file=/Editor.js

https://user-images.githubusercontent.com/16164800/107387571-414c8e00-6af5-11eb-9331-2f6c1b7d288b.mp4

### PR DESCRIPTION
**Pull request by guido-visser**
Fixes #167

### CODE REVIEW

**Comment by guido-visser** [comment]
This makes sure that the options passed to the `setOptions` prop are initialized together with the main SunEditor component

**Comment by mkhstar** [comment]
Hi @guido-visser 
I would like to merge this because i think it is better to setOptions when the editor is initialized. I don't really know if it will break any feature so I have to test it for some time

**Comment by mkhstar** [comment]
The problem you were facing has got to do with attributesWhitelist option
I think when you call the setOptions method with it after it is initialized, it just ignores it

**Comment by mkhstar** [comment]
Thank you

**Pull request merged**
