### PR TITLE
Added Swedish locale

### PR DESCRIPTION
**Pull request by OlehRb**
Awaits for [this pull request](https://github.com/JiHong88/SunEditor/pull/581) to be merged to `SunEditor` package

### CODE REVIEW

**Comment by OlehRb** [comment]
@mkhstar , [this PR](https://github.com/JiHong88/SunEditor/pull/581) was just merged to `SunEditor` package, would you, please, consider merging my PR to provide Swedish local for `suneditor-react`?

**Comment by OlehRb** [comment]
@mkhstar ,ping

**Comment by mkhstar** [comment]
Hi @OlehRb 
Thanks for your contribution but the version of the core suneditor has not been released yet. So if I merge it now I will get an error.

**Comment by OlehRb** [comment]
@mkhstar , Hi again, it looks like the core suneditor was just [released](https://github.com/JiHong88/SunEditor/pull/581#issuecomment-762412061) with those changes, so it is safe to merge them now

**Pull request merged**
