### PR TITLE
Fixed Plugin prop bug by adding a customPlugin prop

### PR DESCRIPTION
**Pull request by Adrian-Jablonski**
Adding plugins as a prop manually causes errors when using the editor. I saw the note “Note that you do not need to pass plugins explicitly from the suneditor package. suneditor-react handles it behind the scenes” but I needed to add custom plugins and there is no way to add custom plugins without using the Plugin prop.

One of the functionality that break when using the plugin prop was image resizing which throws the following error 

`vendors.js:151813 Uncaught TypeError: this.setControllerPosition is not a function`

I found that for some reason this error is caused by the setOptions.plugins condition being run in the below line.
`setOptions.plugins = setOptions.plugins || getPlugins(setOptions);`
But when the plugins are returned from the second condition (getPlugins function), everything works as expected.

The following is what I did to fix this issue

- Created a new prop for the SunEditor component called customPlugins
- Forced plugins to always run through the getPlugins function by omitting the condition that is causing the bug
- Updated the getPlugins function to add what is passed in the customPlugins prop array to the returned array
- In main.js, I pushed the custom plugins to the _plugins array if custom plugins exist

There is now no need to pass anything in the plugin prop. If anything is passed in the prop, it will still give the same errors as it currently does for image resizing. Per the getPlugins function, it will always just load the needed plugins. In addition, any custom plugins will be able to be added when adding them to the customPlugins array. 

 So there is no need to pass anything in the Plugin prop anymore. Using the prop will still cause the same error.
I updated the getPlugins function to append the customPlugins to the returned array. The custom plugins in the array should be added as per http://suneditor.com/sample/html/customPlugins.html

Note: In the main.js file, the only change I made was adding the below to line 14497 after `if (_plugins) {`

`if (options.customPlugins) {
       // Adds the missing customPlugins to the _plugins array to fix custom plugin error
       _plugins.push(...options.customPlugins);
}`

### CODE REVIEW

**Comment by mkhstar** [comment]
Thanks @Adrian-Jablonski,
The setOptions.plugins option was there because i wanted to give explicit plugin definition to the user. But I will go for your suggestion because it is more friendly to use.

**Comment by mkhstar** [comment]
There is a problem with your implementation of options.customPlugins as well because when the user doesn't pass that option to setOptions (in this case it will be undefined), it will throw an error because undefined is not iterable

**Comment by mkhstar** [comment]
But don't worry i will fix that

**Comment by Adrian-Jablonski** [comment]
Your right I did miss that. But thanks for the merge and for fixing it!

**Comment by michelmar** [comment]
@mkhstar
 I use some custom plugins for math, and I would like to have the option to pass as arguments my own plugins, and I would not like to use the customPlugin function because they have the same funcionality as some default plugins. 

Maybe we can use both options. But the way you adopted from here is really limiting the developtment of a custom application.

**Pull request merged**
